'cur is defined' check in removeFragment function
I have the following error in my code without 'cur is defined' validation:
```
(index):53 Error in bootstrap: TypeError: Cannot read properties of null (reading 'nextSibling')
TypeError: Cannot read properties of null (reading 'nextSibling')
    at nextSibling (vue.global.js:9156:33)
    at removeFragment (vue.global.js:7018:22)
    at remove (vue.global.js:6984:15)
    at unmount (vue.global.js:6968:19)
    at unmountComponent (vue.global.js:7040:15)
    at unmount (vue.global.js:6941:15)
    at patch (vue.global.js:5916:15)
    at render (vue.global.js:7088:15)
    at mount (vue.global.js:5371:27)
    at Object.app.mount (vue.global.js:10660:25)
```
This error occurs after site data clearing in "DevTools / Application / Storage" tab:
![screenshot](https://lh5.googleusercontent.com/RJrjDAgx0m_PZDw7zgT5km6u7FrsTHmkH7xl7OtbhXd0b1NNx6eYKjdr3R4Nl6Oo1HueckVwvJffbA=w1921-h847-rw)